const whatsapp = "https://wa.me/5519974066045?text=Olá!%20Vi%20o%20site%20do%20Sonho%20de%20Criança%20e%20gostaria%20de%20solicitar%20um%20orçamento%20para%20uma%20festa.";
function Arrow() { return <span aria-hidden="true">↗</span>; }
function InstagramIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="2" y="2" width="20" height="20" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r="1" className="fill" /></svg>; }
export default function Home() {
  return <main>
    <header className="topbar">
      <a className="brand" href="#inicio" aria-label="Sonho de Criança — início"><img src="/media/logo.png" alt="Sonho de Criança" /></a>
      <nav aria-label="Navegação principal"><a href="#experiencia">A experiência</a><a href="#estrutura">O espaço</a><a href="/cardapios">Cardápios</a><a href="#contato">Contato</a></nav>
      <a className="nav-cta" href={whatsapp} target="_blank" rel="noreferrer">Pedir orçamento <Arrow /></a>
    </header>
    <section className="hero" id="inicio">
      <video autoPlay muted loop playsInline poster="/media/poster.jpg" aria-label="Conheça o espaço Sonho de Criança"><source src="https://sonho-de-crianca-buffet.matheusnastaro5.chatgpt.site/media/sonho-video.mp4" type="video/mp4" /></video><div className="hero-shade" />
      <div className="hero-content"><p className="eyebrow light">Buffet infantil em Piracicaba</p><h1>Sonhos existem<br /><em>para serem realizados.</em></h1><p className="hero-copy">Uma festa vivida por inteiro: as crianças exploram, imaginam e brincam enquanto toda a família celebra junto.</p><div className="hero-actions"><a className="button primary" href={whatsapp} target="_blank" rel="noreferrer">Quero realizar esse sonho <Arrow /></a><a className="text-link" href="#experiencia">Conheça a experiência <span>↓</span></a></div></div>
      <div className="hero-note"><strong>23+</strong><span>anos fazendo<br />parte de histórias</span></div>
    </section>
    <section className="manifesto" id="experiencia">
      <p className="eyebrow">O dia é deles. O momento é de todos.</p><h2>Enquanto eles brincam de verdade,<br /><em>você vive a festa por inteiro.</em></h2><p className="lead">Aniversário de criança passa rápido. Por isso, tudo ao redor precisa abrir espaço para o que importa: os encontros, as risadas e aquela cena que a família vai lembrar por muitos anos.</p>
      <div className="experience-grid"><article className="feature-image tall"><img src="/media/infantil-hd.jpeg" alt="Espaço lúdico infantil com casinhas e mercadinho" /><span>Imaginar</span></article><article className="feature-copy"><span className="number">01</span><h3>Um mundo na altura da imaginação</h3><p>Ambientes pensados para a criança explorar, inventar histórias e aproveitar a festa do jeito mais natural: brincando.</p></article><article className="feature-image"><img src="/media/jogos-hd.jpeg" alt="Área de jogos com pebolim e mesa de sinuca" /><span>Brincar</span></article></div>
    </section>
    <section className="dream-statement"><span>Sonhos existem</span><strong>para serem realizados.</strong></section>
    <section className="space" id="estrutura"><div className="space-image"><img src="/media/ambiente-hd.jpeg" alt="Salão do Sonho de Criança preparado para receber uma festa" /></div><div className="space-copy"><p className="eyebrow">Uma experiência completa</p><h2>Infantil sem deixar de ser <em>elegante.</em></h2><p>O encanto está no equilíbrio: um universo lúdico para quem quer brincar e um ambiente acolhedor para quem quer celebrar. Cada detalhe ajuda a transformar a festa em uma experiência gostosa para todas as idades.</p><ul><li><span>✦</span> Espaços que convidam à descoberta</li><li><span>✦</span> Atmosfera acolhedora para toda a família</li><li><span>✦</span> Uma celebração com personalidade</li></ul><a className="button dark" href={whatsapp} target="_blank" rel="noreferrer">Conversar sobre a minha festa <Arrow /></a></div></section>
    <section className="table-detail"><div><p className="eyebrow">Tudo pronto para receber</p><h2>O cuidado aparece<br /><em>em cada detalhe.</em></h2></div><img src="/media/mesa-hd.jpeg" alt="Mesa posta no salão do Sonho de Criança" /></section>
    <section className="legacy"><div className="legacy-mark">23</div><div><p className="eyebrow light">Desde 2002, em Piracicaba</p><h2>Mais de duas décadas<br />realizando <em>sonhos.</em></h2></div><p>Há histórias que começam com um primeiro aniversário e continuam em muitas outras comemorações. O Sonho de Criança faz parte desses capítulos há mais de 23 anos.</p></section>
    <section className="questions"><div><p className="eyebrow">Antes da festa</p><h2>Vamos começar a imaginar esse dia?</h2></div><div className="faq"><details><summary>Como faço para pedir um orçamento?<span>+</span></summary><p>É só chamar a equipe pelo WhatsApp. Conte a data que você imagina e os primeiros detalhes da comemoração para iniciar a conversa.</p></details><details><summary>Posso conhecer melhor o espaço?<span>+</span></summary><p>Sim. Fale com a equipe pelo WhatsApp para combinar a melhor forma de conhecer o Sonho de Criança.</p></details><details><summary>Onde fica o Sonho de Criança?<span>+</span></summary><p>O buffet fica em Piracicaba, São Paulo. A equipe informa a localização e orientações completas durante o atendimento.</p></details></div></section>
    <section className="final-cta" id="contato"><p className="eyebrow light">A próxima história pode ser a sua</p><h2>Sonhos existem<br /><em>para serem realizados.</em></h2><p>Conte para a gente como você imagina esse dia.</p><a className="button primary" href={whatsapp} target="_blank" rel="noreferrer">Realizar esse sonho pelo WhatsApp <Arrow /></a></section>
    <footer><img src="/media/logo.png" alt="Sonho de Criança" /><p>Buffet infantil · Piracicaba/SP</p><a href="https://instagram.com/sonhodecriancabuffet" target="_blank" rel="noreferrer">@sonhodecriancabuffet</a></footer>
    <a className="instagram-float" href="https://instagram.com/sonhodecriancabuffet" target="_blank" rel="noreferrer" aria-label="Acessar o Instagram do Sonho de Criança"><InstagramIcon /></a>
    <a className="whatsapp-float" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Conversar pelo WhatsApp"><span>WhatsApp</span><b>↗</b></a>
  </main>;
}
